### ISSUE TITLE
Support for Puppet 4.9.x

### ISSUE THREAD

**Issue by m4ce** [ripienaar/puppet-classifier#11]
Looks like classifier is broken on Puppet 4.9.x.

```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Could not autoload /puppet/data_providers/classifier_data_provider_factory: uninitialized constant Puppet::DataProvider
````

**Comment by ripienaar** [comment]
@m4ce yup, this all needs a redo for 4.9 as I was experimenting with non public APIs.  New things exist but 4.9 is not stable yet so not worth spending time right now

**Comment by m4ce** [comment]
Ok, tnx for the answer. I just noticed that Puppet 5 will finally support mapped paths, which is one of the things I was trying to achieve via the classifier.

**Comment by ripienaar** [comment]
This should already be in 4.9 but 4.9 is super broken :(
