### ISSUE TITLE
add in `in` operator

### ISSUE THREAD

**Issue by ripienaar** [ripienaar/puppet-classifier#2]
in a rule it be good to be able to say if `"x"` is in `["x", "y", "z"]`

**Comment by m4ce** [comment]
Would it be possible to have a new release with this feature? I'd love to keep using an official version :)

Thanks!

**Comment by ripienaar** [comment]
@m4ce done :)

**Comment by m4ce** [comment]
@ripienaar, thanks, I guess there was a small problem with the merge. There's a missing closing } in the evaluate_rule.pp:37
