### ISSUE TITLE
Setting hiera values based on classifier

### ISSUE THREAD

**Issue by ggeldenhuis** [ripienaar/puppet-classifier#21]
One of my use cases currently is to check if certain hardware is present and if so include an appropriate class. Specifically checking for FPGA cards. 

When the FPGA cards are added I also need to re-enable a service that is disabled by default based on a list that is set in data directory for the profiles module.

So normally I would just do:
```
profiles::disabled_services::list:
  - "--rpcbind"
  - "--nfs-server"
  - "--nfs"
```

to re-enable certain services based on my hiera hierarchy. However I am reluctant to modify my hierarchy for such a small subset of servers and it would be great if I could use the classifier to set hiera variables. Not sure it is possibly but hopefully the idea is clear.

**Comment by ripienaar** [comment]
Not sure I follow but I imagine you want something like this back? https://github.com/ripienaar/puppet-classifier/commit/3444913bc272e68f32e81429d793e7934eb8ad47

You could do that using a custom hiera backend (https://puppet.com/docs/puppet/6.7/hiera_custom_backends.html) thats built as a puppet function accessing the data hash?

**Comment by ggeldenhuis** [comment]
A bit like that... oh the irony for having removed it.

**Comment by ripienaar** [comment]
Well we removed it because the hiera functions let one do that and better :)

**Comment by gmenuel** [comment]
Hi. I don't know if it can be useful for anybody and/or if this project is still maintained, but I was able to create a simple custom hiera backend that can use the classifier::data hash. If anyone is interrested I can contribute a PR.

**Comment by ripienaar** [comment]
Certainly I am not looking after it anymore - happy to hand to someone else or add colabs who wish to move it forward

**Comment by gmenuel** [comment]
I don't think this module needs to really evolve a lot, it is already working quite fine. I've done a quick PR.
