### ISSUE TITLE
Potential vulnerabilities in Puppet files: Hard-coded Secret

### ISSUE THREAD

**Issue by cantebigene** [ripienaar/puppet-classifier#25]
9 hard-coded secrets were found in 2 different scripts.

Script 1: https://github.com/ripienaar/puppet-classifier/blob/0252ccd35972070281251ee52244e839dcf3a94d/manifests/classify.pp
 - Line [11](https://github.com/ripienaar/puppet-classifier/blob/0252ccd35972070281251ee52244e839dcf3a94d/manifests/classify.pp#L11): `certname=: `
 - Line [23](https://github.com/ripienaar/puppet-classifier/blob/0252ccd35972070281251ee52244e839dcf3a94d/manifests/classify.pp#L23): `certname=: `
 - Line [24](https://github.com/ripienaar/puppet-classifier/blob/0252ccd35972070281251ee52244e839dcf3a94d/manifests/classify.pp#L24): `certname=: `
 - Line [25](https://github.com/ripienaar/puppet-classifier/blob/0252ccd35972070281251ee52244e839dcf3a94d/manifests/classify.pp#L25): `certname=: `

Script 2: https://github.com/ripienaar/puppet-classifier/blob/0252ccd35972070281251ee52244e839dcf3a94d/manifests/init.pp
 - Line [18](https://github.com/ripienaar/puppet-classifier/blob/0252ccd35972070281251ee52244e839dcf3a94d/manifests/init.pp#L18): `certname=' using '`
 - Line [22](https://github.com/ripienaar/puppet-classifier/blob/0252ccd35972070281251ee52244e839dcf3a94d/manifests/init.pp#L22): `certname=' but the active environment is '`
 - Line [26](https://github.com/ripienaar/puppet-classifier/blob/0252ccd35972070281251ee52244e839dcf3a94d/manifests/init.pp#L26): `certname=, environment is `
 - Line [39](https://github.com/ripienaar/puppet-classifier/blob/0252ccd35972070281251ee52244e839dcf3a94d/manifests/init.pp#L39): `certname=: `
 - Line [40](https://github.com/ripienaar/puppet-classifier/blob/0252ccd35972070281251ee52244e839dcf3a94d/manifests/init.pp#L40): `certname=: `

A secret can be a password, user name, or private cryptographic key. 

This type of smell can lead to well-known types of vulnerabilities, as documented by CWE ([CWE-798](https://cwe.mitre.org/data/definitions/798.html) and [CWE-259](https://cwe.mitre.org/data/definitions/259.html)). Hard-coded secrets can be used to bypass protection mechanisms, gain privileges on applications and access to sensitive data. 

Storing secrets in **Puppet** configuration files is considered to be a security smell (cf. [[icse20](https://dl.acm.org/doi/pdf/10.1109/ICSE.2019.00033)]).

**Recommendation**
To protect/manage your secrets, it is recommended to use a vault (e.g., [https://www.vaultproject.io/](https://www.vaultproject.io/)). After configuring the vault, you can replace your secrets by variables from the vault. For instance, replace`$password = ‘12345’` by `$password = $vault::password`. Thus, your secrets will no longer be disclosed publicly.

**Comment by ripienaar** [comment]
Is this some automated spam? Since clearly you made no effort to ensure this is in any way relevant or correct @cantebigene ?
